// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class MyModuleBindings
    {
        readonly ICloudCodeService k_Service;

        public MyModuleBindings() : this(CloudCodeService.Instance) { }

        public MyModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SayHello(string name)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "CrossyRoadServer",
                "SayHello",
                new Dictionary<string, object>()
                {
                    {"name", name},
                });
        }

        public async Task<string> StartRun()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "CrossyRoadServer",
                "StartRun",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<bool> SubmitRunScore(string runId, int score)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "CrossyRoadServer",
                "SubmitRunScore",
                new Dictionary<string, object>()
                {
                    {"runId", runId},
                    {"score", score},
                });
        }
    }
}
